#!/bin/sh

exec "$(fd . "/usr/local/bin/" | awk -F '/' '{print $5}' | rg -i powermenu- | perl -pe 's|powermenu-||g' | BEMENU_SCALE=2 bemenu -p '' -W 0.11 --bdr '#00000000' | perl -pe 's|^|powermenu-|g')"
