#!/usr/bin/perl

my $home = $ENV{"HOME"};

my $lxsessionpid = `pidof lxsession`;
my $picompid = `pidof picom`;
my $dunstpid = `pidof dunst`;
my $polybarpid = `pidof polybar`;

if ($lxsessionpid) {
  print "lxsession already running- not restarting\n";
} else {
  print "starting lxsession...\n";
  system("lxsession &>/dev/null &");
}

if ($picompid) {
  print "picom already running- not restarting\n";
} else {
  print "starting picom...\n";
  system("picom -b &>/dev/null &");
}

if ($dunstpid) {
  print "dunst already running- not restarting\n";
} else {
  print "starting dunst...\n";
  system("dunst &>/dev/null &");
}

if ($polybarpid) {
  print "polybar already running- not restarting\n";
} else {
  print "starting polybar...\n";
  system("/bin/bash $home/.config/launch.sh &>/dev/null &");
}
