#!/usr/bin/perl

use strict;
use warnings;

my $home = $ENV{"HOME"};

my $picom_pid = `pidof picom`;
my $picom_cmd = "picom --config $home/.config/awesome/assets/picom.conf --daemon";
my $gummy_cmd = "gummy -t 5500";

system("gummy start");
system("$gummy_cmd");


if ($picom_pid) {
  system("kill $picom_pid");
  system("sleep 1");
}

system("$picom_cmd");

exit(0);
