#!/usr/bin/luajit

xdgconfighome = os.getenv("XDG_CONFIG_HOME")
xdgcachehome  = os.getenv("XDG_CACHE_HOME")
xdgdatahome   = os.getenv("XDG_DATA_HOME")
windowmanager = os.getenv("DESKTOP_SESSION")
wallpaperdir  = os.getenv("WALLPAPERS_DIR")
scriptsdir    = os.getenv("SCRIPTS_DIR")
screenshotdir = os.getenv("SCREENSHOTS_DIR")
terminal      = os.getenv("TERMINAL")
launcher      = os.getenv("LAUNCHER")
browser       = os.getenv("BROWSER")
editor        = os.getenv("EDITOR")
compositor    = os.getenv("COMPOSITOR")
zdotdir       = os.getenv("ZDOTDIR")
shell         = os.getenv("SHELL")
pwd           = os.getenv("PWD")
