#!/usr/bin/perl

use strict;
use warnings;

my $HOME = $ENV{"HOME"};
my $DATE = system("date +%F_%I-%M-%S");

my $path = "$HOME/Pictures/screenshots/$DATE";
$path =~ s|\n||g;
my $ext = ".png";
print "$path.$ext";
