#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/berry/sxhkdrc &

# Set decoration geometry
berryc border_width       2
berryc inner_border_width 2
berryc title_height       2
berryc top_gap            34

# Set decoration colors
berryc focus_color         2E3436
berryc unfocus_color       272935
berryc inner_focus_color   2E3436
berryc inner_unfocus_color 272935
berryc text_focus_color    ffffff
berryc text_unfocus_color  eeeeec

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Roboto-10"

$XDG_CONFIG_HOME/berry/startup &
